export const SHOPPING_LIST_FETCHING = "SHOPPING_LIST_FETCHING";
export const SHOPPING_LIST_SUCCESS = "SHOPPING_LIST_SUCCESS";
export const SHOPPING_LIST_FAILURE = "SHOPPING_LIST_FAILURE";

export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const REMOVE_ITEM_GROUP_FROM_CART = "REMOVE_ITEM_GROUP_FROM_CART";

export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
